### ISSUE TITLE
Exclude tabs with audio output

### ISSUE THREAD

**Issue by rugk** [autonome/Dormancy#21]
IMHO when you listen to a podcast or so, you would not want that to stop, just because that tab is in the background.

**Comment by autonome** [comment]
I tentatively agree with this.

Given that browsers have visual indicators of tab audio activity now, it's
safer than it used to be to assume the audio is intentional and desired.
Use cases like listening to music in a background tab that is not pinned
will be addressed.

Challenges and downsides:

* Audio means more resource consumption, so not hibernating those tabs
works against some of the use cases for hibernating tabs in the first
places, like increasing battery life.

* What if more than one tab are emitting audio? For a first stab, we'll
keep all of them alive. However, I wonder if research has been done on the
various scenarios where pages emit audio. I also wonder whether the
WebExtensions API for detecting audio uses something like whether a
audio/video source is "playing" or lower system-level detection.

**Comment by rugk** [comment]
> Audio means more resource consumption, so not hibernating those tabs works against some of the use cases for hibernating tabs in the first places

Well, of course, but it suits nobody to have your podcast stopped in the middle (and begin again when restored)…

If you really care, make an option/setting, so users can disable it, if they want.

**Comment by leplatrem** [comment]
I think this is very similar to #10 and maybe solved easily with #7

**Comment by rugk** [comment]
I don't think #2 would help very much, because unlike webrtc I may really use many, many different websites and they may also contain a video/podcast on some pages, but not on all of them.
So a setting for "exclude tabs, which emit sound" may be useful.

BTW are PRs accepted for this? Then I may get to get my hand on this issue.

**Comment by rugk** [comment]
Just saw this should be possible:
* the [tab API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab#Type) exposes `audible` and `mutedInfo`, so that's all we need

**Comment by ole-tange** [comment]
I would prefer a simple way of whitelisting a tab; maybe by clicking an icon next to the location bar.

The reason is that I know what tabs I want to whitelist (i.e. my podcast tab), but there may be many tabs that plays a sound now and then, and I do not want them to be able to decide not to be unloaded. By having a whitelist button I remain in control.

**Comment by rugk** [comment]
> but there may be many tabs that plays a sound now and then

What websites do you visit that do this stuff? IMHO if a website randomly plays a sound _when being in the background_ this is a really bad website design and I would just leave this website, as it would totally annoy me.
Also, playing a sound "now and then" is not enough, it has to play the sound constantly, i.e. play music or something "long".

> I remain in control

In Firefox you can clearly see which tabs are playing sound and thus you know what is "whitelisted". 

As for everything else, I think https://github.com/autonome/Dormancy/issues/7 is the issue you want.

**Comment by ole-tange** [comment]
> What websites do you visit that do this stuff?

Microsoft Outlook Web Access for one. When an email or a reminder is shown it plays a sound. Firefox only shows the loudspeaker icon on the tab while it is playing. This is less than a second.

I would imagine several messaging services running in a browser will do the same.

**Comment by rugk** [comment]
Okay, so a sound does not affect the proposed change at all. The tab would only be "_blacklisted_" while it is playing this sound (i.e. while the sound icon is shown), i.e. in your case it practically would not matter. Note, that each trigger checks the requirements again, so you would have to be very unlucky to catch exactly the second the sound is played to prevent the tab from going to sleep.

See what I said before:

> Also, playing a sound "now and then" is not enough, it has to play the sound constantly, i.e. play music or something "long".
