### ISSUE TITLE
Competition

### ISSUE THREAD

**Issue by rugk** [autonome/Dormancy#37]
Did you see https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/? I was surprised it is actually so much used and is even featured. It does exactly what your add-on does, but has a few more options and such things…

**Comment by Kaos-Industries** [comment]
This is an odd issue to raise. Since when was an extension already existing a reason for another one not to to be developed? Competition is good for the consumer, especially for a niche where competition is already scarce. If there were tens of add-ons that all did the same thing, you might have a point, but there aren't, so you don't.

**Comment by rugk** [comment]
I don't even know what you think my pint is. I am not even sure myself what it is… :laughing: 

I just opened it, because I found this alternative and wanted to make users etc. aware of it, as it has the same features plus a little more and seems to be maintained more frequently…

**Comment by autonome** [comment]
Dormancy, like most of my extensions, is primarily designed for my own use
and experimentation. If others also like them, great.

If you prefer other extensions, I wish you to be happy, so you should use
them instead 😁

**Comment by rugk** [comment]
Yeah… :smile:
