### ISSUE TITLE
Support for whitelisting of domains

### ISSUE THREAD

**Issue by brainstorm** [autonome/Dormancy#7]
I wish some sites could be spared from being forced to sleep... I just lost some form data because of it :/

**Comment by Keith94** [comment]
I support this... @autonome Is this feature planned?

**Comment by autonome** [comment]
This is #2 on my list, just behind configurable timeout for sleep.

**Comment by Grossdm** [comment]
@autonome, I'm also interested in a whitelist.

Disclosure: I am using a different addon with the same goal. I just found this one! 😀

Specifically, a feature that I really would like is to whitelist `moz-extension` tabs.

Do you know if this possible?
A problem a have frequently is editing a userstyle with [Stylus](https://github.com/openstyles/stylus). I hate losing edits to sleepy tabs.
I think [Stylus](https://github.com/openstyles/stylus) unintentionally causes a user (with a dormant tab addon) to lose edits because their addon shows live changes in a tab that matches the userstyle currently being edited.

TIA

**Comment by autonome** [comment]
Hey everyone!

I was thinking about what a reasonable user experience for this would be.

What do you think about a tab context menu option? Eg, "Always keep tabs
from this domain alive" with a checkmark, or something like that?

**Comment by Grossdm** [comment]
Hello @autonome,

I checked on the similar addon that I'm using now - I only use it on Windows, and I'm with my tablet now.

FYI, it is [Auto Tab Discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard). The dev has it in a [GitHub repo](https://github.com/rNeomy/auto-tab-discard) also.

The other dev, rNeomy, has a few options via context menu, including "whitelist the domain" (I don't recall the wording).
I don't think the options are clear with Auto Tab Discard, and I don't think they behave consistently (probably user error with that).

In fact, I think I was in the middle of opening a issue with the addon but I accidentally "discarded" the GitHub tab! IIRC, using his various options via context menu is what got me. In the one instance that I tried to use a harmless menu option, it wasn't available: not greyed out but missing so I clicked the same location on the menu but his options had changed. I think every tab took a dive, despite his unclear whitelist.

I'm sure that's more than enough about someone else's addon, but I thought my experiences with it might help you since you seem to be in a more planning stage of development.

Thanks _very_ much if you're read this far,

Doug®
